### ISSUE TITLE
High CPU and LTeX checking the document every time I open it 

### ISSUE THREAD

**Issue by warpedwood** [valentjn/vscode-ltex#444] opened 2021-10-29 10:02 UTC
**Describe the bug**
LTeX provokes very high CPU and checks the same document every time I open it. It is a long document, more than 50 000 words.

**Steps to reproduce**

1. Open VSCode
2. Activate LTeX

**Expected behavior**
LTeX should check the document rapidly or should not check it again. LTeX should not use so much CPU.

**Sample document**

<details>

```markdown
---
csl: le-tapuscrit-note-modified.csl
bibliography: bibliography.json
link-citations: yes
output: pdf_document
geometry: "margin=2.5cm"
indent: true
linestretch: 1.5
fontfamily: libertine
fontsize: 12pt
documentclass: report
header-includes:
  - \usepackage{setspace}
  - \usepackage{titling}
  - \usepackage{ragged2e}
  - \usepackage[english,spanish,main=french]{babel}
  - \usepackage{fontspec}
  - \usepackage[utf8]{inputenc}
  - \usepackage{csquotes}
  - \usepackage{booktabs}
  - \usepackage{epigraph}
  - \usepackage{etoolbox}
  - \usepackage{array}
  - \usepackage{booktabs}
  - \usepackage{placeins}
  - \usepackage{graphicx}
  - \graphicspath{ {./Images/} }
  - \usepackage{adjustbox}
  - \usepackage{longtable}
  - \usepackage{xltabular}
  - \usepackage[skip=0.5\baselineskip]{caption}
  - \usepackage[bottom,hang,flushmargin]{footmisc}
  - \usepackage{etoc}
  - \usepackage[section]{tocbibind}
  - \usepackage{sectsty}
  - \AtBeginEnvironment{quote}{\par\singlespacing\small}
  - \sectionfont{\centering}
  - \setlength{\skip\footins}{1.2pc plus 5pt minus 2pt}
  - \setlength{\footnotemargin}{0pt}
  - \setlength{\epigraphrule}{0pt}
  - \setlength{\epigraphwidth}{0.6\textwidth}
  - \renewcommand{\textflush}{flushepinormal}
  - \renewcommand\footnotelayout{\hskip5pt}
---
\begin{titlepage}
    \begin{center}


[... truncated]
```

</details>

**LTeX configuration**
Please paste all configuration settings starting with `ltex.` from your `settings.json`. You can help us by temporarily removing some irrelevant settings from your `settings.json` and see if the bug still occurs.

<details>

```
{
  "enabled": [
    "bibtex",
    "html",
    "latex",
    "markdown",
    "org",
    "restructuredtext",
    "rsweave"
  ],
  "language": "auto",
  "dictionary": {},
  "disabledRules": {},
  "enabledRules": {},
  "hiddenFalsePositives": {},
  "bibtex": {
    "fields": {}
  },
  "latex": {
    "commands": {},
    "environments": {}
  },
  "markdown": {
    "nodes": {}
  },
  "configurationTarget": {
    "dictionary": "workspaceFolderExternalFile",
    "disabledRules": "workspaceFolderExternalFile",
    "hiddenFalsePositives": "workspaceFolderExternalFile"
  },
  "additionalRules": {
    "enablePickyRules": false,
    "motherTongue": "fr",
    "languageModel": "",
    "neuralNetworkModel": "",
    "word2VecModel": ""
  },
  "languageToolHttpServerUri": "",
  "languageToolOrg": {
    "username": "",
    "apiKey": ""
  },
  "ltex-ls": {
    "path": "",
    "logLevel": "fine",
    "languageToolHttpServerUri": "",
    "languageToolOrgUsername": "",
    "languageToolOrgApiKey": ""
  },
  "java": {
    "path": "",
    "initialHeapSize": 64,
    "maximumHeapSize": 512
  },
  "sentenceCacheSize": 200000,
  "diagnosticSeverity": "information",
  "checkFrequency": "edit",
  "clearDiagnosticsWhenClosingFile": true,
  "statusBarItem": true,
  "trace": {
    "server": "verbose"
  }
}
```

</details>

**"LTeX Language Server" log file**
First, reproduce the bug. Then, go to `View` → `Output` and select `LTeX Language Server` in the drop-down list. Paste this log here:

<details>

```
[Info  - 11:44:27] Starting ltex-ls...
oct. 29, 2021 11:44:31 AM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: ltex-ls 14.1.0 - initializing...
oct. 29, 2021 11:44:31 AM org.bsplines.ltexls.tools.I18n setLocale
INFO: Setting locale to 'en'
oct. 29, 2021 11:44:31 AM org.bsplines.ltexls.settings.SettingsManager$Companion logDifferentSettings
FINE: Reinitializing LanguageTool due to different settings for language 'auto': setting 'settings', old 'null', new 'non-null'
oct. 29, 2021 11:44:31 AM org.bsplines.ltexls.languagetool.LanguageToolJavaInterface <init>
SEVERE: 'auto' is not a recognized language. Leaving LanguageTool uninitialized, checking disabled.
oct. 29, 2021 11:44:32 AM org.bsplines.ltexls.settings.SettingsManager$Companion logDifferentSettings
FINE: Reinitializing LanguageTool due to different settings for language 'es': setting 'settings', old 'null', new 'non-null'
oct. 29, 2021 11:44:32 AM org.bsplines.ltexls.server.DocumentChecker logTextToBeChecked
FINE: Checking the following text in language 'es' via LanguageTool: "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\\begin{titlepage} \\begin{center}\n\n\n\n\n\n\n\n\n\n"... (truncated to 100 characters)
oct. 29, 2021 11:48:34 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTrace

```

</details>

**"LTeX Language Client" log file**
First, set the `ltex.trace.server` setting in your `settings.json` to `"verbose"`. Then, reload the VS Code window and reproduce the bug. Go to `View` → `Output` and select `LTeX Language Client` in the drop-down list. Paste this log here (note: it will contain your checked document):

<details>

```
2021-10-29T09:44:27.388Z Info: Setting LTeX UI language to 'en-gb'.
2021-10-29T09:44:27.388Z Info: Loading i18n messages...
2021-10-29T09:44:27.391Z Info: Loading default i18n messages...
2021-10-29T09:44:27.394Z Info: 
2021-10-29T09:44:27.394Z Info: ltex.ltex-ls.path not set.
2021-10-29T09:44:27.395Z Info: Searching for ltex-ls in 'c:\Users\xxx\.vscode\extensions\valentjn.vscode-ltex-12.2.0\lib'...
2021-10-29T09:44:27.395Z Info: ltex-ls found in 'c:\Users\xxx\.vscode\extensions\valentjn.vscode-ltex-12.2.0\lib\ltex-ls-14.1.0'.
2021-10-29T09:44:27.395Z Info: 
2021-10-29T09:44:27.395Z Info: Using ltex-ls from 'c:\Users\xxx\.vscode\extensions\valentjn.vscode-ltex-12.2.0\lib\ltex-ls-14.1.0'.
2021-10-29T09:44:27.395Z Info: Using Java bundled with ltex-ls as ltex.java.path is not set.
2021-10-29T09:44:27.396Z Info: Testing ltex-ls...
2021-10-29T09:44:27.396Z Info:   Command: "c:\\Users\\xxx\\.vscode\\extensions\\valentjn.vscode-ltex-12.2.0\\lib\\ltex-ls-14.1.0\\bin\\ltex-ls.bat"
2021-10-29T09:44:27.396Z Info:   Arguments: ["--version"]
2021-10-29T09:44:27.396Z Info:   env['JAVA_HOME']: undefined
2021-10-29T09:44:27.396Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-10-29T09:44:27.962Z Info: Test successful!
2021-10-29T09:44:27.962Z Info: 
2021-10-29T09:44:27.966Z Info: Starting ltex-ls...
2021-10-29T09:44:27.966Z Info:   Command: "c:\\Users\\xxx\\.vscode\\extensions\\valentjn.vscode-ltex-12.2.0\\lib\\ltex-ls-14.1.0\\bin\\ltex-ls.bat"
2021-10-29T09:44:27.966Z Info:   Arguments: []
2021-10-29T09:44:27.966Z Info:   env['JAVA_HOME']: undefined
2021-10-29T09:44:27.966Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-10-29T09:44:27.966Z Info: 
2021-10-29T09:44:31.633Z Info: Started watching external setting file 'c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.dictionary.fr.txt'.
2021-10-29T09:44:31.667Z Info: Started watching external setting file 'c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.en.txt'.
2021-10-29T09:44:31.668Z Info: Started watching external setting file 'c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.fr.txt'.
2021-10-29T09:44:31.674Z Info: Started watching external setting file 'c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.en.txt'.
2021-10-29T09:44:31.675Z Info: Started watching external setting file 'c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.es.txt'.
2021-10-29T09:44:31.677Z Info: Started watching external setting file 'c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.fr.txt'.
2021-10-29T09:48:02.319Z Info: Creating bug report...
2021-10-29T09:48:02.719Z Info: LTeX Status
2021-10-29T09:48:02.719Z Info: ----------------------------------------
2021-10-29T09:48:02.719Z Info: Info about vscode-ltex:
2021-10-29T09:48:02.719Z Info: - Path to extension directory: c:\Users\xxx\.vscode\extensions\valentjn.vscode-ltex-12.2.0
2021-10-29T09:48:02.719Z Info: - Path to directory with LTeX user settings (global storage directory): c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex
2021-10-29T09:48:02.719Z Info: - Path to directory with LTeX workspace settings (for the currently opened workspace): n/a
2021-10-29T09:48:02.719Z Info: - Path to directory with LTeX workspace folder settings (for the workspace folder of the currently active text editor): n/a
2021-10-29T09:48:02.719Z Info: - Version: 12.2.0
2021-10-29T09:48:02.719Z Info: Info about ltex-ls:
2021-10-29T09:48:02.719Z Info: - Version: 14.1.0
2021-10-29T09:48:02.719Z Info: - Process ID: 16392
2021-10-29T09:48:02.719Z Info: - Wall clock duration: 3m31s.012
2021-10-29T09:48:02.719Z Info: - CPU duration: 4m24s.187
2021-10-29T09:48:02.719Z Info: - CPU usage: 27.8%
2021-10-29T09:48:02.719Z Info: - Total allocated memory: 296.75MB
2021-10-29T09:48:02.719Z Info: - Used memory: 270.85MB
2021-10-29T09:48:02.719Z Info: - Is busy checking: true
2021-10-29T09:48:02.719Z Info: - Document URI being checked: file:///c%3A/Users/xxx/Documents/markdown.md
2021-10-29T09:48:02.719Z Info: Currently watched external setting files:
2021-10-29T09:48:02.719Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.dictionary.fr.txt
2021-10-29T09:48:02.719Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.en.txt
2021-10-29T09:48:02.719Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.fr.txt
2021-10-29T09:48:02.719Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.en.txt
2021-10-29T09:48:02.719Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.es.txt
2021-10-29T09:48:02.719Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.fr.txt
2021-10-29T09:48:02.719Z Info: ----------------------------------------
2021-10-29T09:48:32.829Z Info: Creating bug report...
2021-10-29T09:48:32.861Z Info: LTeX Status
2021-10-29T09:48:32.861Z Info: ----------------------------------------
2021-10-29T09:48:32.861Z Info: Info about vscode-ltex:
2021-10-29T09:48:32.861Z Info: - Path to extension directory: c:\Users\xxx\.vscode\extensions\valentjn.vscode-ltex-12.2.0
2021-10-29T09:48:32.861Z Info: - Path to directory with LTeX user settings (global storage directory): c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex
2021-10-29T09:48:32.861Z Info: - Path to directory with LTeX workspace settings (for the currently opened workspace): n/a
2021-10-29T09:48:32.861Z Info: - Path to directory with LTeX workspace folder settings (for the workspace folder of the currently active text editor): n/a
2021-10-29T09:48:32.861Z Info: - Version: 12.2.0
2021-10-29T09:48:32.861Z Info: Info about ltex-ls:
2021-10-29T09:48:32.861Z Info: - Version: 14.1.0
2021-10-29T09:48:32.861Z Info: - Process ID: 16392
2021-10-29T09:48:32.861Z Info: - Wall clock duration: 4m01s.507
2021-10-29T09:48:32.861Z Info: - CPU duration: 4m54s.859
2021-10-29T09:48:32.861Z Info: - CPU usage: 12.7%
2021-10-29T09:48:32.861Z Info: - Total allocated memory: 325.06MB
2021-10-29T09:48:32.861Z Info: - Used memory: 259.64MB
2021-10-29T09:48:32.861Z Info: - Is busy checking: true
2021-10-29T09:48:32.861Z Info: - Document URI being checked: file:///c%3A/Users/xxx/Documents/markdown.md
2021-10-29T09:48:32.861Z Info: Currently watched external setting files:
2021-10-29T09:48:32.861Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.dictionary.fr.txt
2021-10-29T09:48:32.862Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.en.txt
2021-10-29T09:48:32.862Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.fr.txt
2021-10-29T09:48:32.862Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.en.txt
2021-10-29T09:48:32.862Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.es.txt
2021-10-29T09:48:32.862Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.fr.txt
2021-10-29T09:48:32.862Z Info: ----------------------------------------
[Trace - 11:48:34] Sending notification '$/setTrace'.
Params: {
    "value": "verbose"
}


[Trace - 11:48:34] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "ltex": {
            "enabled": [
                "bibtex",
                "html",
                "latex",
                "markdown",
                "org",
                "restructuredtext",
                "rsweave"
            ],
            "language": "auto",
            "dictionary": {},
            "disabledRules": {},
            "enabledRules": {},
            "hiddenFalsePositives": {},
            "bibtex": {
                "fields": {}
            },
            "latex": {
                "commands": {},
                "environments": {}
            },
            "markdown": {
                "nodes": {}
            },
            "configurationTarget": {
                "dictionary": "workspaceFolderExternalFile",
                "disabledRules": "workspaceFolderExternalFile",
                "hiddenFalsePositives": "workspaceFolderExternalFile"
            },
            "additionalRules": {
                "enablePickyRules": false,
                "motherTongue": "fr",
                "languageModel": "",
                "neuralNetworkModel": "",
                "word2VecModel": ""
            },
            "languageToolHttpServerUri": "",
            "languageToolOrg": {
                "username": "",
                "apiKey": ""
            },
            "ltex-ls": {
                "path": "",
                "logLevel": "fine",
                "languageToolHttpServerUri": "",
                "languageToolOrgUsername": "",
                "languageToolOrgApiKey": ""
            },
            "java": {
                "path": "",
                "initialHeapSize": 64,
                "maximumHeapSize": 512
            },
            "sentenceCacheSize": 200000,
            "diagnosticSeverity": "information",
            "checkFrequency": "edit",
            "clearDiagnosticsWhenClosingFile": true,
            "statusBarItem": true,
            "trace": {
                "server": "verbose"
            }
        }
    }
}


2021-10-29T09:48:42.227Z Info: Creating bug report...
[Trace - 11:48:42] Sending request 'workspace/executeCommand - (4)'.
Params: {
    "command": "_ltex.getServerStatus",
    "arguments": []
}


[Trace - 11:48:42] Received response 'workspace/executeCommand - (4)' in 34ms.
Result: {
    "success": true,
    "processId": 16392,
    "wallClockDuration": 250.903,
    "cpuUsage": 0.12493669630139935,
    "cpuDuration": 304.25,
    "usedMemory": 282066280,
    "totalMemory": 325058560,
    "isChecking": true,
    "documentUriBeingChecked": "file:///c%3A/Users/xxx/Documents/markdown.md"
}


2021-10-29T09:48:42.261Z Info: LTeX Status
2021-10-29T09:48:42.261Z Info: ----------------------------------------
2021-10-29T09:48:42.261Z Info: Info about vscode-ltex:
2021-10-29T09:48:42.261Z Info: - Path to extension directory: c:\Users\xxx\.vscode\extensions\valentjn.vscode-ltex-12.2.0
2021-10-29T09:48:42.261Z Info: - Path to directory with LTeX user settings (global storage directory): c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex
2021-10-29T09:48:42.261Z Info: - Path to directory with LTeX workspace settings (for the currently opened workspace): n/a
2021-10-29T09:48:42.261Z Info: - Path to directory with LTeX workspace folder settings (for the workspace folder of the currently active text editor): n/a
2021-10-29T09:48:42.261Z Info: - Version: 12.2.0
2021-10-29T09:48:42.261Z Info: Info about ltex-ls:
2021-10-29T09:48:42.261Z Info: - Version: 14.1.0
2021-10-29T09:48:42.261Z Info: - Process ID: 16392
2021-10-29T09:48:42.261Z Info: - Wall clock duration: 4m10s.902
2021-10-29T09:48:42.261Z Info: - CPU duration: 5m04s.250
2021-10-29T09:48:42.261Z Info: - CPU usage: 12.5%
2021-10-29T09:48:42.261Z Info: - Total allocated memory: 325.06MB
2021-10-29T09:48:42.261Z Info: - Used memory: 282.07MB
2021-10-29T09:48:42.261Z Info: - Is busy checking: true
2021-10-29T09:48:42.261Z Info: - Document URI being checked: file:///c%3A/Users/xxx/Documents/markdown.md
2021-10-29T09:48:42.261Z Info: Currently watched external setting files:
2021-10-29T09:48:42.261Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.dictionary.fr.txt
2021-10-29T09:48:42.261Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.en.txt
2021-10-29T09:48:42.261Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.fr.txt
2021-10-29T09:48:42.261Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.en.txt
2021-10-29T09:48:42.261Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.es.txt
2021-10-29T09:48:42.261Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.fr.txt
2021-10-29T09:48:42.261Z Info: ----------------------------------------
2021-10-29T09:50:28.267Z Info: Creating bug report...
[Trace - 11:50:28] Sending request 'workspace/executeCommand - (5)'.
Params: {
    "command": "_ltex.getServerStatus",
    "arguments": []
}


[Trace - 11:50:28] Received response 'workspace/executeCommand - (5)' in 38ms.
Result: {
    "success": true,
    "processId": 16392,
    "wallClockDuration": 356.948,
    "cpuUsage": 0.13201671603956686,
    "cpuDuration": 416.25,
    "usedMemory": 288913208,
    "totalMemory": 330301440,
    "isChecking": true,
    "documentUriBeingChecked": "file:///c%3A/Users/xxx/Documents/markdown.md"
}


2021-10-29T09:50:28.305Z Info: LTeX Status
2021-10-29T09:50:28.305Z Info: ----------------------------------------
2021-10-29T09:50:28.305Z Info: Info about vscode-ltex:
2021-10-29T09:50:28.306Z Info: - Path to extension directory: c:\Users\xxx\.vscode\extensions\valentjn.vscode-ltex-12.2.0
2021-10-29T09:50:28.306Z Info: - Path to directory with LTeX user settings (global storage directory): c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex
2021-10-29T09:50:28.306Z Info: - Path to directory with LTeX workspace settings (for the currently opened workspace): n/a
2021-10-29T09:50:28.306Z Info: - Path to directory with LTeX workspace folder settings (for the workspace folder of the currently active text editor): n/a
2021-10-29T09:50:28.306Z Info: - Version: 12.2.0
2021-10-29T09:50:28.306Z Info: Info about ltex-ls:
2021-10-29T09:50:28.306Z Info: - Version: 14.1.0
2021-10-29T09:50:28.306Z Info: - Process ID: 16392
2021-10-29T09:50:28.306Z Info: - Wall clock duration: 5m56s.947
2021-10-29T09:50:28.306Z Info: - CPU duration: 6m56s.250
2021-10-29T09:50:28.306Z Info: - CPU usage: 13.2%
2021-10-29T09:50:28.306Z Info: - Total allocated memory: 330.30MB
2021-10-29T09:50:28.306Z Info: - Used memory: 288.91MB
2021-10-29T09:50:28.306Z Info: - Is busy checking: true
2021-10-29T09:50:28.306Z Info: - Document URI being checked: file:///c%3A/Users/xxx/Documents/markdown.md
2021-10-29T09:50:28.306Z Info: Currently watched external setting files:
2021-10-29T09:50:28.306Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.dictionary.fr.txt
2021-10-29T09:50:28.306Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.en.txt
2021-10-29T09:50:28.306Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.disabledRules.fr.txt
2021-10-29T09:50:28.306Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.en.txt
2021-10-29T09:50:28.306Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.es.txt
2021-10-29T09:50:28.306Z Info: - c:\Users\xxx\AppData\Roaming\Code\User\globalStorage\valentjn.vscode-ltex\ltex.hiddenFalsePositives.fr.txt
2021-10-29T09:50:28.306Z Info: ----------------------------------------
2021-10-29T09:50:46.395Z Info: Creating bug report...
[Trace - 11:50:46] Sending request 'workspace/executeCommand - (6)'.
Params: {
    "command": "_ltex.getServerStatus",
    "arguments": []
}



```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: Windows_NT (win32), x64, 10.0.22000
- VS Code: 1.61.2
- vscode-ltex: 12.2.0
- ltex-ls: 14.1.0
- Java: 11.0.12

**Additional context/information**
You can add any other context or information about the problem here.

**Comment by valentjn** [comment] 2021-10-29 11:12
I'm not sure I understand what the problem is. When you open a document, LT<sub>E</sub>X checks it of course. And if it's a long document, [this will take some time](https://valentjn.github.io/ltex/faq.html#why-does-ltex-have-such-a-high-cpu-load).

After that initial check, it should be very fast when editing the document, provided that it fits into the sentence cache, which it does as you increased [`ltex.sentenceCacheSize`](https://valentjn.github.io/ltex/settings.html#ltexsentencecachesize) to 200,000. But I guess that's not an issue as the server log you posted indicates that the initial check has not been completed yet (4mins after the check started, which is indeed very long). In that case, the size of the sentence cache is irrelevant.

If you don't want the document to be checked, add a magic comment at the beginning (`% ltex: enabled=false`).

If you want the document to be checked, but faster, then you should split up your document into multiple files, which is best practice for a number of reasons anyway (clarity, version control, incremental compiling, sharing with other people, etc.). I couldn't stay on top of things with such a large document. Usually, you don't need to have the whole document checked at once, only the part you're currently working on.

If you don't want to split up your file, you can use magic comments to just check the part you're interested in:

```latex
% beginning of file
% ltex: enabled=false
[stuff before the part to be checked]
% ltex: enabled=true
[part to be checked]
% ltex: enabled=false
[stuff after the part to be checked]
```

**Comment by valentjn** [comment] 2021-10-29 11:16
There's also the possibility of setting [`ltex.checkFrequency`](https://valentjn.github.io/ltex/settings.html#ltexcheckfrequency) to `manual`. Then, documents won't be checked when opened, and you need to run [`LTeX: Check Current Document`](https://valentjn.github.io/ltex/vscode-ltex/commands.html#ltex-check-current-document) to check the document if you're ready (which will of course take some time, if the document is very long).

**Comment by warpedwood** [comment] 2021-10-29 12:18
Thank you for your detailed answer. Indeed, I tried to modify the cache to see if it was solving the problem, but as you say it doesn't come from there. What I found strange is that the document was checked before and every time I open it is fully checked again and thus provokes high CPU usage. Maybe shifting the setting `ltex.checkFrequency` to `manual` can be a good idea.

**Comment by valentjn** [comment] 2021-10-30 07:31
FWIW, it's also possible to use [`LTeX: Check Selection`](https://valentjn.github.io/ltex/vscode-ltex/commands.html#ltex-check-selection) to check only the selected text. In combination with `"ltex.checkFrequency": "manual"`, this might fulfill your needs.

**Comment by valentjn** [comment] 2021-11-04 09:14
Closing as expected behavior (see [known limitations](https://valentjn.github.io/ltex/vscode-ltex/contributing.html#known-issues-and-limitations) and [FAQ](https://valentjn.github.io/ltex/faq.html#why-does-ltex-have-such-a-high-cpu-load)). The long checking time is exclusively caused upstream (LanguageTool). Any performance bottlenecks that can be improved should be reported over at [LanguageTool](https://github.com/languagetool-org/languagetool).

**Closed as completed by valentjn** 2021-11-04 09:14 UTC
Labels: 1-bug 🐛, 2-unconfirmed, 3-not-a-bug, 2-upstream
