### ISSUE TITLE
enable/disable with comment currently works only if on a separate line

### ISSUE THREAD

**Issue by Reissner** [valentjn/vscode-ltex#638] opened 2022-06-17 08:49 UTC
Note: It is highly recommended to follow the instructions at https://valentjn.github.io/ltex/vscode-ltex/contributing.html#how-to-report-bugs and use the `LTeX: Report bug in LTeX` command from within Visual Studio Code. Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Describe the bug**
This is something between bug and feature request: 
Via comments `% LTeX: enabled=false/true` one can disable/enable LTeX. 
The problem is, that this seems to work only if this is on a separate line. 
For example 
```
Type 
% LTeX: enabled=false
\texttt{setArithmetics(Double);x=pn(800000)}. 
% LTeX: enabled=true
to change arithmetic type. 
```
works, whereas 
```
Type % LTeX: enabled=false
\texttt{setArithmetics(Double);x=pn(800000)}. % LTeX: enabled=true
to change arithmetic type. 
```
does not. 
I think the latter should work also, because it keeps the source more readable 
and there are occasions where it is difficult to place enablement/disablement on a separate line: 
Here, in the first example LTeX warns me that the sentence starts with lower case letter ('to change...'). 
For example

**Steps to reproduce**
Very simple to reproduce: just use the two above examples: 
In the first LTeX warnings are disabled, whereas in the second one they are not. 

**Expected behavior**
I would expect/wish that LTeX warnings are disabled in both cases. 

**Sample document**
```
\documentclass{article}
\begin{document}
Type % LTeX: enabled=false
\texttt{setArithmetics(Double);x=pn(800000)}. % LTeX: enabled=true
\end{document}
```

<details>

Bug/Behavior is even without special config: 
```
```

The next two pieces of information are irrelevant in this case. 

**Version information**
List here the version information of the relevant software.

- Operating system: suse tumbleweed current (2022-06-17)
- VS Code: 1.68.1
- vscode-ltex: 13.1.0
- Java: openjdk 11.0.15

**Additional context/information**
You can add any other context or information about the problem here.

**Comment by valentjn** [comment] 2022-06-17 09:04
I'd find this confusing.
```latex
Type % LTeX: enabled=false
```
on a separate line looks to me like LT<sub>E</sub>X is disabled for only this single line, i.e., only for `Type`. I wouldn't expect this to be the start of a disabled block. Other linters have similar syntaxes (e.g., mypy's `# type: ignore` to ignore Python type warnings on a single line of Python code).

**Comment by valentjn** [comment] 2022-06-17 09:06
This is not a bug, as [this behavior is documented](https://valentjn.github.io/ltex/advanced-usage.html#magic-comments) (&ldquo;Except when otherwise noted, magic comments have to be on their own line, [...]&rdquo;).

**Comment by valentjn** [comment] 2022-06-22 08:52
Closing as out-of-scope as outlined above. To hide a single diagnostic, there's already the &ldquo;Hide false positive&rdquo; quick fix, so the use case for this would be pretty narrow anyway.

**Closed as not planned by valentjn** 2022-06-22 08:52 UTC
Labels: 1-feature-request ✨, 3-out-of-scope
