### ISSUE TITLE
Check Plaintext/.txt files

### ISSUE THREAD

**Issue by hpvd** [valentjn/vscode-ltex#352] opened 2021-07-09 08:42 UTC
**Is your feature request related to a problem? Please describe.**
vs code now has with this great extension a great tool to check spelling and grammar.
In the simplest usecase "writing txt files", one still writes with spelling and grammar errors :-)

**Describe the solution you'd like**
Check Plaintext/.txt files by default
Should be technical easy and would give great benefit

**Describe alternatives you've considered**
have no check 

**Additional context**
none

**Comment by valentjn** [comment] 2021-07-09 09:53
This is already possible, just add `"plaintext"` to [`ltex.enabled`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexenabled) (you might have to activate the extension manually as mentioned there). As to why it's not checked by default, see https://github.com/valentjn/vscode-ltex/issues/4#issuecomment-529433416 &mdash; note that it wasn't possible to add specific languages to `ltex.enabled` back then. Closing as duplicate of #19, this is where this got introduced.

**Closed as completed by valentjn** 2021-07-09 09:53 UTC
Labels: 1-feature-request ✨, 3-duplicate

**Comment by valentjn** [comment] 2021-07-12 19:29
Duplicate of #19
