### ISSUE TITLE
Change position of grammer correction in context menu

### ISSUE THREAD

**Issue by nikchha** [valentjn/vscode-ltex#129] opened 2020-09-27 12:39 UTC
**Situation**

Currently, the option to correct a word is the last option in the context menu. 

![image](https://user-images.githubusercontent.com/37020365/94365143-cb5c0300-00ce-11eb-90e0-a05650b155f0.png)

**Feature Request**

To quickly correct a typo, it would be nice to have the correct functionality as the first option in the context. This would enable a quick CMD + . + Enter shortcut to correct a typo.

**Comment by valentjn** [comment] 2020-09-27 12:59
Thanks for the feature request. But why not just press `↑` to select the last option in the context menu?

Apart from that, there's a reason behind the current order, which is that there can be many suggestions at the same time, and the top entries of a context menu are always visible, even if it doesn't fit on the screen:

![vscode-ltex-129](https://user-images.githubusercontent.com/19839841/94365437-3c041f00-00d1-11eb-89f6-cbceaac47faf.png)

What would you suggest in this case?

(The example here was `This is a mna.`, but the same scenario occurs if you select a long document via `Cmd+A` and request quick fixes for the whole document via `Cmd+.`.)

**Comment by nikchha** [comment] 2020-09-27 13:20
Thank you! I see your reasoning behind the context menu order. 

However, your suggested ↑ solution does not work for me. I am not quite sure if its a bug with my setup.

**Comment by valentjn** [comment] 2020-09-27 18:42
`↑` works at least on Windows and Linux. The selection will wrap around on these systems, i.e., `↑` selects the last item of the context menu if the first one was selected, and vice-versa with `↓`. Unfortunately, I don't have a Mac at hand to test it there.

Theoretically, another option would be grouping all the suggestions (or all but the first few) into a submenu, so that the suggestions could be moved to the top. However, the Language Server Protocol only allows the specification of a list of quick fixes, i.e., without nesting.

So I'm not sure what I can do here...

**Comment by nikchha** [comment] 2020-09-28 10:58
I just checked on my Windows/Ubuntu setup and can confirm that your solution works perfectly there. However, on my main MacOS device, it does not work. Maybe it's indeed an issue with the macOS distribution of vscode.

I really like the idea of nesting the suggestions but I guess it's unlikely that the LSP will allow for nesting soon.

Anyway - thank you very much!

**Comment by valentjn** [comment] 2020-09-28 14:50
No worries. Closing this for now--either request a selection wrapping feature in macOS (maybe it can be implemented for VS Code/Electron only), or a nesting feature in LSP.

**Closed as completed by valentjn** 2020-09-28 14:50 UTC
Labels: 1-feature-request ✨, 3-duplicate

**Comment by valentjn** [comment] 2021-04-22 17:54
This came up in a second issue (#297). The order is now swapped, so this is fixed. Marking this issue as duplicate since the discussion in the other issue is longer. Thanks for the suggestion.

**Comment by valentjn** [comment] 2021-05-05 07:46
Duplicate of #297
