### ISSUE TITLE
LTeX not spell-checking

### ISSUE THREAD

**Issue by asterikx** [valentjn/vscode-ltex#17] opened 2019-10-31 17:20 UTC
**Describe the bug**
My tex files are *not* getting spell-checked.

**Steps to reproduce**
1. Install LTeX
2. Install LTeX language extension (English)

**Expected behavior**
My tex files are getting spell-checked.

**LTeX configuration**
```
    "ltex.enabled": true,
    "ltex.language": "en-US",
```

**Version information**
- VS Code: 1.39.2
- LTeX: 4.7.5
- LTeX language extensions: English/4.7.4
- Java: 11.0.2

**Additional context/information**
I tried restarting VSCode several times without success.

**Comment by valentjn** [comment] 2019-11-10 18:42
@asterikx That's too little information to reproduce the issue for me. (I have VS Code 1.39.2 and Java 11.0.5, which is pretty similar, and it works for me, obviously.)

* Which OS do you use (+version)? If Linux, which distribution?
* Can you update to LT<sub>E</sub>X 4.7.6, set `ltex.trace.server` to `"verbose"`, restart VS Code, reproduce the issue by loading a *.tex file, look in `View` → `Output` → `LTeX Language Server`/`LTeX Language Client`, and paste all relevant output here? Thank you!

**Comment by asterikx** [comment] 2019-11-10 19:47
@valentjn Thanks for your effort!

I'm using MacOS 10.15.1, and the problem obviously is related to [jEnv](http://www.jenv.be) which I use to manage Java versions

LTeX Language Server/LTeX Language Client output:
```
ERROR: JAVA_HOME is set to an invalid directory: /Users/asterikx/.jenv/versions/system

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

The directory `/Users/asterikx/.jenv/versions/system` does indeed not exist.

I don't why it is trying to use that directory since jEnv is set 11.0.2.
```
asterikx@MBP ~ % jenv version 
11.0.2 (set by /Users/asterikx/.jenv/version)
asterikx@MBP ~ % java -version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
asterikx@MBP ~ % echo $JAVA_HOME
/Users/asterikx/.jenv/versions/11.0.2
```

I don't know if the problem is related to the extension or VSCode itself. And  I don't know where it reading `/Users/asterikx/.jenv/versions/system` from.

Also it seems to ignore the java.home set in the VSCode settings 
```
"java.home": "/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home",
```

**Comment by valentjn** [comment] 2019-11-10 21:30
@asterikx I don't know much about macOS, and jEnv is completely unknown to me. [Googling](https://www.google.com/search?hl=en&q=%22java_home%22%20%22.jenv%2Fversions%2Fsystem%22) suggests this might occur [if you have a `.java-version` file somewhere](https://github.com/jenv/jenv/issues/188#issuecomment-457083881). jEnv seems to be changing `JAVA_HOME` dynamically based on that. It looks like you ran `echo $JAVA_HOME` and the other stuff in `~`, which is maybe not where the *.tex file is or where VS Code has been started from (not sure which one is more important). `grep`ping for  `.jenv/versions/` might help you find the culprit.

The `java.home` setting is from the Java extension pack and sets the Java path for writing Java programs in VS Code, so it is unrelated to LT<sub>E</sub>X. The Java path for executing Java programs like LT<sub>E</sub>X's Java component should be set with `JAVA_HOME`.

I'm voting to close this issue as it seems to be unrelated to LT<sub>E</sub>X.

**Closed as completed by valentjn** 2019-11-10 21:30 UTC
Labels: 1-bug 🐛, 3-not-a-bug

**Comment by valentjn** [comment] 2020-02-14 19:10
FYI PR #24 added a new setting, `ltex.javaHome`, which overrides the value of `JAVA_HOME`.
