### ISSUE TITLE
Language is set to ru-RU but LTeX checks document in en-US

### ISSUE THREAD

**Issue by helviett** [valentjn/vscode-ltex#351] opened 2021-07-08 01:10 UTC

**Comment by valentjn** [comment] 2021-07-08 06:50
This is due to the `\selectlanguage{english}` in your document (line 33) and [LT<sub>E</sub>X's babel support](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#multilingual-latex-documents-with-the-babel-package). LT<sub>E</sub>X cannot see that it's inside a `\newenvironment` definition as [LT<sub>E</sub>X is not a L<sup>A</sup>T<sub>E</sub>X compiler](https://valentjn.github.io/vscode-ltex/docs/contributing-code-issues.html#known-issues-and-limitations). Add a [magic comment](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#magic-comments) (`% ltex: language=ru-RU`) after the environment definition to workaround this, or put your preamble in a different file, which is recommended anyway.

Closing as intended behavior.

Note: You might want to remove your personal info from the bug report.

**Closed as completed by valentjn** 2021-07-08 06:50 UTC
Labels: 1-bug 🐛, 2-unconfirmed, 3-not-a-bug
