### ISSUE TITLE
Support to LanguageTool subscription

### ISSUE THREAD

**Issue by mhalano** [valentjn/vscode-ltex#398] opened 2021-08-28 11:28 UTC
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
Using actual real-world examples that explain why you and many other users would benefit from the feature increases the request's chances of being implemented.
I subscribed to the paid version of LanguageTool. It provides more complete suggestions than the basic version. I would like to be able to log in to my account and get these more complete suggestions, in the same way I do when I use the Firefox extension.

**Describe the solution you'd like**
Implement option to do the login and get the advanced suggestions available for subscribers.

**Describe alternatives you've considered**
Can't find any alternatives.

**Additional context**

**Comment by valentjn** [comment] 2021-08-28 11:47
Unless you're a subscriber of the API plan, this is a duplicate of [#18](https://github.com/valentjn/vscode-ltex/discussions/18), i.e., this is not possible with a simple Premium plan of LanguageTool. You need an API plan instead, as only this plan allows third-party access to LanguageTool Premium. See also [the docs](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#languagetool-http-servers).

**Comment by mhalano** [comment] 2021-08-28 21:09
I opened an issue with the developer so we could find a way to query using login options to get answers using the premium features. https://github.com/languagetool-org/languagetool/issues/5587

**Comment by valentjn** [comment] 2021-08-28 21:29
You can open an upstream issue, but as I said, you have to [subscribe to an API plan](https://languagetool.org/proofreading-api) for this to work (for me, it says EUR 29 per month for 100 checks per day). It's simply not allowed in the normal Premium plan for external software to access LT Premium features via HTTP. That's what the API plan is for.

**Comment by mhalano** [comment] 2021-08-29 15:27
@valentjn I got an API key. But I just could set the API endpoint, not the API key. There is an option which just can be set editing the JSON config file?

**Comment by valentjn** [comment] 2021-08-29 15:41
Ah, I see. This has to be implemented on LT<sub>E</sub>X side. Sorry for the confusion.

**Comment by valentjn** [comment] 2021-08-30 10:48
`ltex.ltex-ls.languageToolOrgUsername` and `ltex.ltex-ls.languageToolOrgApiKey` are now implemented. @mhalano Can you try the [nightly](https://github.com/valentjn/vscode-ltex/releases) to see if it's working? I don't have an API key.

**Comment by mhalano** [comment] 2021-08-30 11:27
@valentjn Installed the nightly version and configured username and API key. What can I do to check if the extension is querying the API endpoint correctly?

**Comment by valentjn** [comment] 2021-08-30 16:07
Check sentences that contain diagnostics that only LanguageTool Premium discovers. [Their website](https://languagetool.org/premium?force_language=1) contains some examples:

```plaintext
He was very afraid of the consequences.
If that's not possible what are our options?
The children have been saved by the police.
etc.
```

I don't get a diagnostic for any of these (without API key). You might want to set [`ltex.checkFrequency`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexcheckfrequency) to `"manual"` first to avoid hitting your rate limit.

**Comment by mhalano** [comment] 2021-08-30 17:16
I thought it had a debug option to describe the connection process. I got two of three corrections. Seems good to me. What do you think? Can we mark as solved?
![image](https://user-images.githubusercontent.com/6025031/131378245-11a7f5c5-8ad1-49e6-aa8e-089220c27360.png)

**Comment by valentjn** [comment] 2021-08-30 18:20
Excellent, it seems to be working. It might be that some of those examples only work when activating picky rules via [`ltex.additionalRules.enablePickyRules`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexadditionalrulesenablepickyrules), or when enabling the corresponding rules manually via [`ltex.enabledRules`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexenabledrules).

The documentation will be updated to include the new settings once released. Thanks for the feature request.

**Closed as completed by valentjn** 2021-08-30 18:20 UTC
Labels: 1-feature-request ✨, 3-fixed

**Comment by valentjn** [comment] 2021-10-14 14:59
Feature released in 12.0.0.

**Comment by melsophos** [comment] 2022-05-31 19:55
Just for reference for people who need it (see also #18), it is possible to request an API key as a Premium user by contacting the support, there is no need to have a developer plan.

**Comment by bobek** [comment] 2022-11-30 12:49
Just for the reference, it seems that you don't need to contact support anymore. There is a settings page, which allows for generating the token directly:

![image](https://user-images.githubusercontent.com/26891/204800176-05bc2abd-9065-44b4-9eed-443eebdb5ecf.png)

I had to set `languageToolHttpServerUri` to `https://api.languagetoolplus.com`  (without `v2`).
