### ISSUE TITLE
Why does "Check Current Document" no work?

### ISSUE THREAD

**Issue by grivasgervilla** [valentjn/vscode-ltex#506] opened 2022-01-02 19:26 UTC
### Discussed in https://github.com/valentjn/vscode-ltex/discussions/505

<div type='discussions-op-text'>

<sup>Originally posted by **Griger** January  2, 2022</sup>
I am editing a LaTeX document and I want to check spelling errors automatically, but it does not occur.

I can check some selections with the "Check Selection" command and when I open a new document and start to write, this works and the spelling errors are highlighted. However, in this document this does not occur.

Is it due to the file length? Is there some LaTeX code that makes LTeX not working? I have installed VS Code LTeX today, so I have not added this file to any exception rule or something like that...

Many thanks for your time.</div>

**Comment by valentjn** [comment] 2022-01-02 19:54
Duplicate of #505

**Closed as completed** 2022-01-02 19:55 UTC
Labels: 3-duplicate
