### ISSUE TITLE
Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by sschaenz** [valentjn/vscode-ltex#650] opened 2022-06-27 16:38 UTC
**Describe the bug**

After a while, the checking stops. In the log the message “Header must provide a Content-Length property.” can be seen many times.  In the city line, the “wheel” of the LTex check is turning. It looks to me like the communication to the server is not working. When I quit VSC and restart, it works again for a while.

**Steps to reproduce**

Unfortunately, I could not provoke the error myself. It always occurs after some (different) time. The text is also not very long. It currently consists of 3900 words (German/English).

**Expected behavior**

I expect the check function to work reliably. In case of problems, the user should be pointed out; otherwise he will deliver texts with flaws.

**Sample document**

I don't think there is an issue with the text. It is a German text with numerous English terms (IT). It is Markdown, although so far, only two headings are in Markdown; otherwise it is “normal” text.

**LTeX configuration**

<details>

```
"ltex.additionalRules.motherTongue": "de-DE",
    "ltex.language": "de-DE",
    "ltex.statusBarItem": true,
    "ltex.enabledRules": {
        "de-DE": ["TOO_LONG_PARAGRAPH", "STYLE_REPEATED_WORD_RULE_DE", "PASSIVE_SENTENCE_DE", "FILLER_WORDS_DE", "WHITESPACE_PARAGRAPH", " GENDER_NEUTRALITY", "REDUNDANCY"]
        },    

"ltex.diagnosticSeverity" : {
        "GERMAN_SPELLER_RULE" : "error", 
        "FILLER_WORDS_DE" : "hint",
        "default":"information",
    },
```

</details>

**“LTeX Language Server” log file**
First, reproduce the bug. Then, go to `View` → `Output` and select `LTeX Language Server` in the drop-down list. Paste this log here:

<details>

```
REPLACE_THIS_WITH_LTEX_LANGUAGE_SERVER_LOG
```

</details>

**“LTeX Language Client” log file**

<details>

```
2022-06-27T16:21:29.177Z Info: Setting LTeX UI language to 'de'.
2022-06-27T16:21:29.177Z Info: Loading i18n messages...
2022-06-27T16:21:29.177Z Info: Loading default i18n messages...
2022-06-27T16:21:29.179Z Info: 
2022-06-27T16:21:29.179Z Info: ltex.ltex-ls.path not set.
2022-06-27T16:21:29.179Z Info: Searching for ltex-ls in '/Users/myuser/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib'...
2022-06-27T16:21:29.180Z Info: ltex-ls found in '/Users/myuser/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0'.
2022-06-27T16:21:29.180Z Info: 
2022-06-27T16:21:29.180Z Info: Using ltex-ls from '/Users/myuser/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0'.
2022-06-27T16:21:29.180Z Info: Using Java bundled with ltex-ls as ltex.java.path is not set.
2022-06-27T16:21:29.235Z Info: Testing ltex-ls...
2022-06-27T16:21:29.235Z Info:   Command: "/Users/myuser/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls"
2022-06-27T16:21:29.235Z Info:   Arguments: ["--version"]
2022-06-27T16:21:29.235Z Info:   env['JAVA_HOME']: undefined
2022-06-27T16:21:29.235Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2022-06-27T16:21:29.845Z Info: Test successful!
2022-06-27T16:21:29.848Z Info: 
2022-06-27T16:21:29.851Z Info: Starte ltex-ls ...
2022-06-27T16:21:29.851Z Info:   Command: "/Users/myuser/.vscode/extensions/valentjn.vscode-ltex-13.1.0/lib/ltex-ls-15.2.0/bin/ltex-ls"
2022-06-27T16:21:29.851Z Info:   Arguments: []
2022-06-27T16:21:29.851Z Info:   env['JAVA_HOME']: undefined
2022-06-27T16:21:29.851Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2022-06-27T16:21:29.851Z Info: 
[Trace - 6:21:29 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 16111,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.68.1"
    },
    "locale": "de",
    "rootPath": "/Volumes/DATA/",
    "rootUri": "file:///Volumes/DATA/",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
...

```

</details>

**Version information**

- Operating system: macOS 12.4 (Intel)
- VS Code: 1.68.1
- vscode-ltex: 13.1.0
- ltex-ls: 15.2.0
- Java: openjdk 18.0.1.1 2022-04-22

**Additional context/information**

Unfortunately I could not reproduce the error yet. I had the message "Header must provide a Content-Length property."

**Comment by sschaenz** [comment] 2022-06-27 16:55
I was able to reproduce the behavior with bug report #511. Possibly, it is the same issue.

You get the error message under “runtime status”, not in the log.

Paste this in the editor with de_De conf. and hit return.

```

EBenfalls Wird

```

Result in "Header must provide a Content-Length property." message seen in "Errors not caught (22)"

**Comment by valentjn** [comment] 2022-06-27 17:48
Duplicate of #511

**Closed as completed** 2022-06-27 17:49 UTC
Labels: 1-bug 🐛, 2-unconfirmed, 3-duplicate
